version: "3.8"

services:
  ##########################################################
  ####################### Mosquitto ########################
  ##########################################################
  mqtt:
    image: eclipse-mosquitto:2
    user: mosquitto
    volumes:
      - type: bind
        source: ./config/mqtt/config
        target: /mosquitto/config/
      - type: bind
        source: ./config/mqtt/log/
        target: /mosquitto/log/
      - type: volume
        source: data
        target: /mosquitto/data/
    ports:
      - target: 1883
        published: 1883
        protocol: tcp
        mode: host
      - target: 9001
        published: 9001
        protocol: tcp
        mode: host
    networks:
      - data_sources

  ##########################################################
  ######################### NodeRed ########################
  ##########################################################
  nodered:
    image: nodered/node-red:latest
    container_name: nodered
    environment:
      - TZ=Africa/Casablanca
    ports:
      - "1880:1880"
    #network_mode: host
    volumes:
      - ./nodered/data:/data
    healthcheck:
      interval: 5s
      timeout: 3s
      retries: 5
      test: [ "CMD", "curl", "-f", "http://nodered:1880" ]

  ##########################################################
  ################### IoTSensorsMQTT-SIM ###################
  ##########################################################
  ioTSensorsMQTT-Sim1:
    image: amineamaach/sensors-mqtt:v1.0.0
    restart: always
    container_name: iot-sensors-sim1
    volumes:
      - ./config/iot-sensorsMQTT/iot-sensors-sim1.json:/configs/config.json
    network_mode: host

  ioTSensorsMQTT-Sim2:
    image: amineamaach/sensors-mqtt:v1.0.0
    restart: always
    container_name: iot-sensors-sim2
    volumes:
      - ./config/iot-sensorsMQTT/iot-sensors-sim2.json:/configs/config.json
    network_mode: host

  ioTSensorsMQTT-Sim3:
    image: amineamaach/sensors-mqtt:v1.0.0
    restart: always
    container_name: iot-sensors-sim3
    volumes:
      - ./config/iot-sensorsMQTT/iot-sensors-sim3.json:/configs/config.json
    network_mode: host

  ioTSensorsMQTT-Sim4:
    image: amineamaach/sensors-mqtt:v1.0.0
    restart: always
    container_name: iot-sensors-sim4
    volumes:
      - ./config/iot-sensorsMQTT/iot-sensors-sim4.json:/configs/config.json
    network_mode: host

  ioTSensorsMQTT-Sim5:
    image: amineamaach/sensors-mqtt:v1.0.0
    restart: always
    container_name: iot-sensors-sim5
    volumes:
      - ./config/iot-sensorsMQTT/iot-sensors-sim5.json:/configs/config.json
    network_mode: host

  ##########################################################
  ################ packml-simulator ########################
  ##########################################################
  #cnc
  berlin-cnc-line1:
    container_name: berlin-cnc-line1
    image: spruiktec/packml-simulator
    environment:
      SITE: "berlin"
      AREA: "cnc"
      LINE: "line_1"
      MQTT_URL: mqtt://localhost
      CLIENT_TYPE: mqtt
    mem_limit: 30MB
    restart: always
    network_mode: host

  berlin-cnc-line2:
    container_name: berlin-cnc-line2
    image: spruiktec/packml-simulator
    environment:
      SITE: "berlin"
      AREA: "cnc"
      LINE: "line_2"
      MQTT_URL: mqtt://localhost
      CLIENT_TYPE: mqtt
    mem_limit: 30MB
    restart: always
    network_mode: host

  berlin-cnc-line3:
    container_name: berlin-cnc-line3
    image: spruiktec/packml-simulator
    environment:
      SITE: "berlin"
      AREA: "cnc"
      LINE: "line_3"
      MQTT_URL: mqtt://localhost
      CLIENT_TYPE: mqtt
    mem_limit: 30MB
    restart: always
    network_mode: host

  # electronic_assembly
  berlin-electronic_assembly-line1:
    container_name: berlin-electronic_assembly-line1
    image: spruiktec/packml-simulator
    environment:
      SITE: "berlin"
      AREA: "electronic_assembly"
      LINE: "line_1"
      MQTT_URL: mqtt://localhost
      CLIENT_TYPE: mqtt
    mem_limit: 30MB
    restart: always
    network_mode: host

  berlin-electronic_assembly-line2:
    container_name: berlin-electronic_assembly-line2
    image: spruiktec/packml-simulator
    environment:
      SITE: "berlin"
      AREA: "electronic_assembly"
      LINE: "line_2"
      MQTT_URL: mqtt://localhost
      CLIENT_TYPE: mqtt
    mem_limit: 30MB
    restart: always
    network_mode: host

  berlin-electronic_assembly-line3:
    container_name: berlin-electronic_assembly-line3
    image: spruiktec/packml-simulator
    environment:
      SITE: "berlin"
      AREA: "electronic_assembly"
      LINE: "line_3"
      MQTT_URL: mqtt://localhost
      CLIENT_TYPE: mqtt
    mem_limit: 30MB
    restart: always
    network_mode: host

  #mechanical_assembly
  berlin-mechanical_assembly-line1:
    container_name: berlin-mechanical_assembly-line1
    image: spruiktec/packml-simulator
    environment:
      SITE: "berlin"
      AREA: "mechanical_assembly"
      LINE: "line_1"
      MQTT_URL: mqtt://localhost
      CLIENT_TYPE: mqtt
    mem_limit: 30MB
    restart: always
    network_mode: host

  berlin-mechanical_assembly-line2:
    container_name: berlin-mechanical_assembly-line2
    image: spruiktec/packml-simulator
    environment:
      SITE: "berlin"
      AREA: "mechanical_assembly"
      LINE: "line_2"
      MQTT_URL: mqtt://localhost
      CLIENT_TYPE: mqtt
    mem_limit: 30MB
    restart: always
    network_mode: host

  berlin-mechanical_assembly-line3:
    container_name: berlin-mechanical_assembly-line3
    image: spruiktec/packml-simulator
    environment:
      SITE: "berlin"
      AREA: "mechanical_assembly"
      LINE: "line_3"
      MQTT_URL: mqtt://localhost
      CLIENT_TYPE: mqtt
    mem_limit: 30MB
    restart: always
    network_mode: host

  #packaging
  berlin-packaging-line1:
    container_name: berlin-packaging-line1
    image: spruiktec/packml-simulator
    environment:
      SITE: "berlin"
      AREA: "packaging"
      LINE: "line_1"
      MQTT_URL: mqtt://localhost
      CLIENT_TYPE: mqtt
    mem_limit: 30MB
    restart: always
    network_mode: host

  berlin-packaging-line2:
    container_name: berlin-packaging-line2
    image: spruiktec/packml-simulator
    environment:
      SITE: "berlin"
      AREA: "packaging"
      LINE: "line_2"
      MQTT_URL: mqtt://localhost
      CLIENT_TYPE: mqtt
    mem_limit: 30MB
    restart: always
    network_mode: host

  berlin-packaging-line3:
    container_name: berlin-packaging-line3
    image: spruiktec/packml-simulator
    environment:
      SITE: "berlin"
      AREA: "packaging"
      LINE: "line_3"
      MQTT_URL: mqtt://localhost
      CLIENT_TYPE: mqtt
    mem_limit: 30MB
    restart: always
    network_mode: host

  ###############################################################
  ################# Power Generators Simulators #################
  ###############################################################
  pgmqtt-cnc:
    image: amineamaach/simulators-pgmqtt:v1.0.0
    restart: always
    container_name: pgmqtt-cnc
    volumes:
      - ./config/pgmqtt/pgmqtt-berlin1.json:/config/config.json
    environment:
      MQTT_SERVER_URL: mqtt://localhost:1883
      SITE: 'berlin'
      AREA: 'powergenerator/cnc_pg'
      MQTT_CLIENT_ID: 'cnc_pg'
      RANDOM_DELAY_BETWEEN_MESSAGES: 'true'
      DELAY_BETWEEN_MESSAGES_MIN: 3
      DELAY_BETWEEN_MESSAGES_MAX: 15
      GENERATORS_NUMBER: 4
    network_mode: host

  pgmqtt-electronic_assembly:
    image: amineamaach/simulators-pgmqtt:v1.0.0
    restart: always
    container_name: pgmqtt-electronic_assembly
    volumes:
      - ./config/pgmqtt/pgmqtt-berlin2.json:/config/config.json
    environment:
      MQTT_SERVER_URL: mqtt://localhost:1883
      SITE: 'berlin'
      AREA: 'powergenerator/electronic_assembly_pg'
      MQTT_CLIENT_ID: 'electronic_assembly_pg'
      RANDOM_DELAY_BETWEEN_MESSAGES: 'true'
      DELAY_BETWEEN_MESSAGES_MIN: 5
      DELAY_BETWEEN_MESSAGES_MAX: 10
      GENERATORS_NUMBER: 4
    network_mode: host

  pgmqtt-mechanical_assembly:
    image: amineamaach/simulators-pgmqtt:v1.0.0
    restart: always
    container_name: pgmqtt-mechanical_assembly
    volumes:
      - ./config/pgmqtt/pgmqtt-berlin3.json:/config/config.json
    environment:
      MQTT_SERVER_URL: mqtt://localhost:1883
      SITE: 'berlin'
      AREA: 'powergenerator/mechanical_assembly_pg'
      MQTT_CLIENT_ID: 'mechanical_assembly_pg'
      RANDOM_DELAY_BETWEEN_MESSAGES: 'true'
      DELAY_BETWEEN_MESSAGES_MIN: 5
      DELAY_BETWEEN_MESSAGES_MAX: 10
      GENERATORS_NUMBER: 4
    network_mode: host

  pgmqtt-packaging_power:
    image: amineamaach/simulators-pgmqtt:v1.0.0
    restart: always
    container_name: pgmqtt-mechanical_assembly
    volumes:
      - ./config/pgmqtt/pgmqtt-berlin4.json:/config/config.json
    environment:
      MQTT_SERVER_URL: mqtt://localhost:1883
      SITE: 'berlin'
      AREA: 'powergenerator/packaging_power_pg'
      MQTT_CLIENT_ID: 'packaging_power_pg'
      RANDOM_DELAY_BETWEEN_MESSAGES: 'true'
      DELAY_BETWEEN_MESSAGES_MIN: 5
      DELAY_BETWEEN_MESSAGES_MAX: 10
      GENERATORS_NUMBER: 4
    network_mode: host

volumes:
  node-red-data:
  mosquitto-data:
  data:
    name: "mqtt-broker-data"

networks:
  data_sources:
    name: data_sources
    driver: bridge
  nodered-net:
