version: "3.8"
services:
  lenses:
    image: lensesio/box
    environment:
      EULA: ""
      LENSES_SECURITY_USER: admin
      LENSES_SECURITY_PASSWORD: admin
    ports:
      - 3030:3030
      - 9991:9991
      - 9102:9102
